#!/bin/bash

# colour
fg="#c8c8c8"
fgy="#272432"
bg="#131313"
bgh="#7E9C80"
bgw="#BFBEC3"
geo="1920x30+0+0"
fd="-*-terminal-*-*-*-*-14-*-*-*-*-*-*-*"
fs="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"

bar="-g ${geo} -f ${fd} -f ${fs} -F ${fg} -B ${bg}"

wrk(){
    desk=$(xdotool get_desktop)
    case $desk in
        0) echo "%{B$bgh}%{F$fgy} 1 %{B$bgw}%{F$fgy} 2  3  4 %{F-}%{B-}  ";;
        1) echo "%{B$bgw}%{F$fgy} 1 %{B$bgh}%{F$fgy} 2 %{B$bgw}%{F$fgy} 3  4 %{F-}%{B-} ";;
        2) echo "%{B$bgw}%{F$fgy} 1  2 %{B$bgh}%{F$fgy} 3 %{B$bgw}%{F$fgy} 4 %{F-}%{B-} ";;
        3) echo "%{B$bgw}%{F$fgy} 1  2  3 %{B$bgh}%{F$fgy} 4 %{F-}%{B-} ";;
    esac
}

#task(){
#    id=$(xtitle)
#    echo -n "%{F#BFBEC3} $id %{F-}"
#}

ram(){
	mem=$(free | awk '/Mem/{print $3/$2 * 100}' | cut -d'.' -f1)
	echo -n "%{B#896E72}%{F$fgy}  %{B#BFBEC3}%{F$fgy} $mem% %{F-}%{B-}"
}

vol(){
	VOL=$(amixer get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}')
	if [ $VOL = '0%' ]; then
		echo -n "%{B#637B81}%{F$fgy}  %{B#BFBEC3}%{F$fgy} M %{F-}%{B-}"
	else
		echo -n "%{B#637B81}%{F$fgy}  %{B#BFBEC3}%{F$fgy} $VOL %{F-}%{B-}"
	fi
}

bat() {
    percent=$(cat /sys/class/power_supply/BAT1/capacity)
    status=$(cat /sys/class/power_supply/BAT1/status)

    if test $status = "Charging"; then
        echo -n "%{B#B29C7C}%{F$fgy}  %{F-}"
    elif test $status = "Full"; then
        echo -n "%{B#B29C7C}%{F$fgy}  %{F-}"
    else
        if test $percent -gt 60; then
            echo -n "%{B#B29C7C}%{F$fgy}  %{F-}"
        elif test $percent -gt 25; then
            echo -n "%{B#B29C7C}%{F$fgy}  %{F-}"
        else
            echo -n "%{B#B29C7C}%{F$fgy}  %{F-}%{B-}"
        fi
    fi
    echo -e "%{B#BFBEC3}%{F$fgy} $percent% %{F-}%{B-}"
}

wifi(){
    net=$(/sbin/iwconfig wlp63s0 |grep ESSID| awk '{print $NF}'|cut -d ":" -f 2)
    echo -n "%{B#5A8585}%{F$fgy}  %{B#BFBEC3}%{F$fgy} $net %{F-}%{B-}"
}

clock(){
	time=$(date "+%H:%M")
	echo -n "%{A:$HOME/Scripts/bin/calendar:}%{B#7E9C80}%{F$fgy}  %{B#BFBEC3}%{F$fgy} $time %{F-}%{B-}%{A} "
}

while true; do
	echo "%{l}$(wrk) %{r}$(ram) $(vol) $(bat) $(wifi) $(clock) "
	sleep 1
done | lemonbar ${bar} | sh & > /dev/null
