#!/bin/bash
# https://askubuntu.com/questions/518928/how-to-write-a-script-to-listen-to-battery-status-and-alert-me-when-its-above

while true
do
    battery_level=$(cat /sys/class/power_supply/BAT1/capacity)
    if ! on_ac_power; then
        if [ $battery_level -le 20 ]; then
            notify-send "Battery is low" "Please plug in AC adapter. Current battery level ${battery_level}%"
        fi
    fi

    sleep 300 
done
