#!/bin/bash

# Take screen shot
scrot /tmp/screen.png

# Pixelate screen shot
convert -scale 20% -scale 500% /tmp/screen.png /tmp/screen-pixelate.png

# Grab and resize lock image (this could be a random image)
convert ~/.utility/assets/lock-icon.png -resize 300 /tmp/lock-icon.png 

# Will need to check the resized image does not exceed 1080 pixels in height if it is radomized
convert /tmp/screen-pixelate.png /tmp/lock-icon.png -gravity center -composite /tmp/screen-lock.png

# Lock the screen
i3lock -u -e -i /tmp/screen-lock.png -n

# Clean up
rm /tmp/screen.png
rm /tmp/screen-pixelate.png
rm /tmp/screen-lock.png
