#!/bin/bash

scrot /tmp/screen.png

convert -scale 20% -scale 500% /tmp/screen.png /tmp/screen-pixelate.png

i3lock -u -e -i /tmp/screen-pixelate.png -n

rm /tmp/screen.png
rm /tmp/screen-pixelate.png
