#!/bin/bash

# Exit if already running
# https://askubuntu.com/questions/157779/how-to-determine-whether-a-process-is-running-or-not-and-make-use-it-to-make-a-c
if pgrep -x "i3lock" > /dev/null
then
    exit 0 # Exit with no errors
fi

# Take screen shot
scrot /tmp/screen.png

# Pixelate screen shot
convert /tmp/screen.png -scale 20% -scale 500% /tmp/screen-pixelate.png

# Grab and resize lock image (this could be a random image)
convert ~/.utility/assets/lock-icon.png -resize 300 /tmp/lock-icon.png 

# Will need to check the resized image does not exceed 1080 pixels in height if it is radomized
convert /tmp/screen-pixelate.png /tmp/lock-icon.png -gravity center -composite /tmp/screen-lock.png

# Lock the screen
i3lock -u -e -i /tmp/screen-lock.png -n

rm /tmp/screen.png
rm /tmp/screen-pixelate.png
rm /tmp/screen-lock.png
